---
# Maqueta de documento

# Opciones de pandoc para la configuración de la maqueta LaTex.
# Referencia
# https://pandoc.org/MANUAL.html#variables-for-latex

lang: es-MX

documentclass: book

classoption:
- onecolumn
- 12pt
- oneside
- letterpaper
#- notitlepage

# geometry:
# - width=129mm
# - top=25mm
# - bottom=25mm
# - headheight=15pt

# Table of contents
toc: true

# Figures and tables
lof: true
lot: true

hyperrefoptions:
- breaklinks=true
#- linktoc=all
#- pdfwindowui
#- pdfpagemode=FullScreen

link-citations: true
linkcolor: magenta
urlcolor: blue
citecolor: black
toccolor: black
urlstyle: tt
links-as-notes: true

indent: true
#pagestyle: plain
#papersize: letterpaper
#secnumdepth: 3

biblatexoptions:
- backend=biber
- sorting=nyt

# Cuando se llama pandoc con --natbib y --biblatex
#biblio-style: authoryear
#biblio-title: Bibliografía

# Este valor ya está incluido en la Makefile
# utilizando la flag --bibliography y la variable BIBLIO
#bibliography: sources.bib

# Fuentes
fonaatfamily: libertine
fontfamily: inconsolata
mainfont: Linux Libertine
monofont: Inconsolata
...
