module Sound.RTG.Ritmo.RhythmicPattern where
{-|
Module      : RhythmicPattern
Description : Main data type and its API helper functions
Copyright   : (c) Xavier Góngora, 2023
License     : GPL-3
Maintainer  : ixbalanque@protonmail.ch
Stability   : experimental

Rhythmic patterns are wrapped patterns with aditional structure.
-}

import           Data.Group                     (Group, invert)
import           Sound.RTG.Ritmo.Pattern        (Pattern, Time)
import           Sound.RTG.Ritmo.PerfectBalance (indicatorVector)

-- | This data type represents integers modulo 2
data Binary = Zero | One

instance Show Binary where
  show Zero = show 0
  show One = show 1

instance Semigroup Binary where
  Zero <> One  = One
  One  <> Zero = One
  _    <> _    = Zero

instance Monoid Binary where
  mempty = Zero

instance Group Binary where
  invert  = id

-- | Onset patterns are represented by binary valued lists
-- so that group structure can de lifted.
type OnsetPattern = Pattern Binary

-- | Groupings of pattern onsets generated by the
-- mutual nearest-neighbor graph.
type Groupings a = [Pattern a]

type OnsetGroups = Groupings Binary

-- | Meter carries musical context information
-- related to a patterns underlying pulse.
type Meter = Int

-- | This data type encondes a rhythmic pattern along with
-- other structure related to rhythm perception.
data Rhythmic = Rhythm {
                        pttrn  :: OnsetPattern,
                        groups :: OnsetGroups,
                        meter  :: !Meter
                       }

instance Show Rhythmic where
  show rhythm = show (pttrn rhythm)

toRhythm :: Pattern Time -> Rhythmic
toRhythm xs = Rhythm {
                      pttrn = toOnset (indicatorVector xs),
                      groups = [],
                      meter = length xs
                     }

mutualNNG :: Pattern Bool -> Groupings Bool
mutualNNG xs = []

toOnset :: Pattern Int -> OnsetPattern
toOnset = map (\n -> if (== 0) . (`mod` 2) $ n then Zero else One)
